#!/usr/bin/env bash
# MAF (Multi-Agent Framework) + MEA one-click installer for OpenClaw
# Usage:
#   bash install.sh                 # install for current user
#   OPENCLAW_HOME=/path bash install.sh
#   AGENCY_AGENTS_HOME=/path bash install.sh
set -e

echo "=== MAF v2.3 + MEA installer ==="
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"
PM_WORKSPACE="${PM_WORKSPACE:-$OPENCLAW_HOME/workspace-pm}"
AGENCY_AGENTS_HOME="${AGENCY_AGENTS_HOME:-$HOME/agency-agents-zh}"
AGENCY_REPO="${AGENCY_REPO:-https://github.com/jnMetaCode/agency-agents-zh.git}"

echo "OPENCLAW_HOME       = $OPENCLAW_HOME"
echo "PM_WORKSPACE        = $PM_WORKSPACE"
echo "AGENCY_AGENTS_HOME  = $AGENCY_AGENTS_HOME"
echo ""

# 0. check OpenClaw
if [ ! -d "$OPENCLAW_HOME" ]; then
  echo "❌ OpenClaw home not found: $OPENCLAW_HOME"
  echo "   Install OpenClaw first, or set OPENCLAW_HOME."
  exit 1
fi

mkdir -p "$PM_WORKSPACE/skills" "$PM_WORKSPACE/outputs"

# 1. install maf + maf-trigger skill (workspace-pm level)
echo "📦 Installing skills to $PM_WORKSPACE/skills/ ..."
rm -rf "$PM_WORKSPACE/skills/maf" "$PM_WORKSPACE/skills/maf-trigger"
cp -r "$SCRIPT_DIR/skills/maf" "$PM_WORKSPACE/skills/maf"
cp -r "$SCRIPT_DIR/skills/maf-trigger" "$PM_WORKSPACE/skills/maf-trigger"

# 2. install PM workspace personality files (AGENTS.md / SOUL.md / IDENTITY.md / TOOLS.md / HEARTBEAT.md / USER.md)
if [ -d "$SCRIPT_DIR/pm-workspace-template" ]; then
  echo "🧠 Installing PM workspace template files ..."
  for f in AGENTS.md SOUL.md IDENTITY.md TOOLS.md HEARTBEAT.md; do
    if [ -f "$SCRIPT_DIR/pm-workspace-template/$f" ]; then
      # 不覆盖已有的，避免把用户自己改过的覆盖掉
      if [ -f "$PM_WORKSPACE/$f" ]; then
        echo "   - keep existing $f"
      else
        cp "$SCRIPT_DIR/pm-workspace-template/$f" "$PM_WORKSPACE/$f"
        echo "   + installed $f"
      fi
    fi
  done
  # USER.md 只在不存在时安装模板
  if [ ! -f "$PM_WORKSPACE/USER.md" ] && [ -f "$SCRIPT_DIR/pm-workspace-template/USER.md" ]; then
    cp "$SCRIPT_DIR/pm-workspace-template/USER.md" "$PM_WORKSPACE/USER.md"
    echo "   + installed USER.md template (edit it with your own info)"
  fi
fi

# 3. clone 215-role agent library
if [ -d "$AGENCY_AGENTS_HOME/.git" ]; then
  echo "📚 Role library already exists at $AGENCY_AGENTS_HOME — pulling latest ..."
  git -C "$AGENCY_AGENTS_HOME" pull --ff-only || echo "   ⚠️ pull failed, keep current version"
elif [ -d "$AGENCY_AGENTS_HOME" ]; then
  echo "📚 $AGENCY_AGENTS_HOME exists but is not a git repo — leave it as is."
else
  echo "📚 Cloning 215-role library to $AGENCY_AGENTS_HOME ..."
  git clone --depth 1 "$AGENCY_REPO" "$AGENCY_AGENTS_HOME"
fi

# 4. write env file so PM agent can read paths
ENV_FILE="$PM_WORKSPACE/maf-env.sh"
cat > "$ENV_FILE" <<EOF
# Source this file to expose MAF paths to sub-shells / sub-agents.
# Generated by install.sh on $(date -Iseconds 2>/dev/null || date).
export OPENCLAW_HOME="$OPENCLAW_HOME"
export PM_WORKSPACE="$PM_WORKSPACE"
export AGENCY_AGENTS_HOME="$AGENCY_AGENTS_HOME"
export MAF_OUTPUT_ROOT="$PM_WORKSPACE/outputs"
# Optional: point AnySearch to a non-default location
# export ANYSEARCH_HOME="\$HOME/.openclaw/workspace/skills/anysearch"
EOF
echo "📝 Wrote $ENV_FILE"

# 5. AnySearch hint (do not auto-install without asking)
ANYSEARCH_DEFAULT="$HOME/.openclaw/workspace/skills/anysearch"
echo ""
if [ -f "$ANYSEARCH_DEFAULT/scripts/anysearch_cli.py" ] || [ -n "$ANYSEARCH_HOME" ] && [ -f "$ANYSEARCH_HOME/scripts/anysearch_cli.py" ]; then
  echo "✅ AnySearch detected."
else
  echo "ℹ️  AnySearch not found at $ANYSEARCH_DEFAULT"
  echo "   MAF uses AnySearch for web research. To install it in OpenClaw, say:"
  echo "      clawhub install anysearch"
  echo "   Or set ANYSEARCH_HOME if you have it elsewhere."
fi

# 6. final hints
echo ""
echo "=== ✅ MAF v2.3 + MEA installed ==="
echo ""
echo "Next steps:"
echo "  1. Restart OpenClaw (or reload skills)."
echo "  2. Make sure PM agent's workspace is: $PM_WORKSPACE"
echo "  3. In the PM conversation, say:"
echo "       启动多智能体：<your task>"
echo "     or:"
echo "       /maf <your task>"
echo ""
echo "Doctor (verify all dependencies):"
echo "    bash scripts/doctor.sh"
echo ""
echo "Files installed:"
find "$PM_WORKSPACE/skills/maf" "$PM_WORKSPACE/skills/maf-trigger" -type f 2>/dev/null \
  | sed "s|$PM_WORKSPACE/|  |" | sort
